### ISSUE TITLE
flex:1 on Button

### ISSUE THREAD

**Issue by saravanabalagi** [avocode/nachos-ui#59]
In the button component, `.container {flex:1}` is not friendly to existing components and causes serious layout issues. I believe it should be changed and should not take as much space by default. 

Current behavior

![image](https://user-images.githubusercontent.com/8567893/66607756-da3f6200-ebac-11e9-955f-8b18a5e8cea0.png)

Code:
```jsx
<View styleName="container">
        <FontAwesomeIcon icon={faCoffee}/>
        <Text>Welcome</Text>
        <Button>Proceed</Button>
        <Input placeholder='someone@email.com'/>
</View>
```
```css
.container {
  flex: 1;
  justify-content: center;
  align-items: center;
  background-color: #EEE;
}
```

Expected: Button in the middle of the screen

Linked: #11.
